/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_UserProfileI (void);
GtkWidget* create_SignUpI (void);
GtkWidget* create_signInI (void);
GtkWidget* create_deleteAlert (void);
GtkWidget* create_updateAlertI (void);
GtkWidget* create_adminCitoyen (void);
GtkWidget* create_sendEmail (void);
GtkWidget* create_adminDashboardI (void);
GtkWidget* create_citoyenDashboardI (void);
